#Administrador de Scripts de las aplicaciones que se encuentran en la carpeta Public
DEFAULT:
	JS:
		JQUERY:			'Public/js/jquery-1.8.3.Dev.js'
		VALIDATE:		'Public/js/jquery.validate.js'
	CSS:
		HOME:			'Public/Neural/css/Default.css'
	LOADER:
		LOADER: 		'Public/images/Load/neural_load.gif'
		CLASS:
			IMAGEN:		{ CLASS: 'DESACTIVADO', STYLE: 'DESACTIVADO' }
			CONTENEDOR:	{ CLASS: 'DESACTIVADO', STYLE: 'DESACTIVADO' }
		STYLE:
			IMAGEN:		{ border: '0px', font-family: 'verdana', width: '25px', height: '25px' }
			CONTENEDOR:	{ border: '0px', font-family: 'verdana', text-align: 'center' }

MI_APLICACION:
	JS:
		JQUERY:			'Public/js/jquery-1.8.3.Dev.js'
		VALIDATE:		'Public/js/jquery.validate.js'
	CSS:
		HOME:			'Public/Neural/css/styles.css'
	LOADER:
		LOADER: 		'Public/images/Load/neural_load.gif'
		CLASS:
			IMAGEN:		{ CLASS: 'DESACTIVADO', STYLE: 'DESACTIVADO' }
			CONTENEDOR:	{ CLASS: 'DESACTIVADO', STYLE: 'DESACTIVADO' }
		STYLE:
			IMAGEN:		{ border: '0px', font-family: 'verdana' }
			CONTENEDOR:	{ border: '0px', font-family: 'verdana' }
